{% set name = "threedigrid" %}
{% set version = "1.0.15" %}
{% set sha256 = "13c19e0feb5d18e01cd1146b79bf075ec57e79d6f1c753ecff5df608297eaca5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - 3digrid_explore = threedigrid.management.commands.kick:kick_start
    - 3digrid_export = threedigrid.management.commands.kick:export_to

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.13
    - h5py >=2.7.1
    - cftime >=1.0.1
    - click >=6.0
    - mercantile >=1.0.1
    - pyproj >=1.9.5.1
    - shapely >=1.6.4
    - geojson >=2.3.0

test:
  imports:
    - threedigrid

about:
  home: https://github.com/nens/threedigrid
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python package for the threedigrid administration'
  description: |
    Features: access to the threedicore administration by a single instance of 
    the GridH5Admin object, query the model data by pre-defined subsets and django
    style filters,  export model data to gis formats like shapefile and geopackage,
    serialize model data as geojson
  doc_url: https://threedigrid.readthedocs.io/
  dev_url: https://github.com/nens/threedigrid

extra:
  recipe-maintainers:
    - caspervdw
    - larsclaussen
    - jpprins1
    - byrman
