travis:
  secure:
    BINSTAR_TOKEN: cERVbjdCBj6oK1Rb9ro9f8xA0Mfta15nG62xnNFrKGh0F0QZ1pXcpo8iQMtBCvJpJzo5DywHloiDiydc0Af2+cQ14knAH2FhVxH6U6FuBy/TEJcv9RwliK6TITX8Npx2+CxD08WvvegTcSGXyA9Mh7CR1O2VuRTwIwAb5CqgazSD3lE8ZSH1jhI865yQ2zLoVzJhmsIlZbndTAtCPG5Zyb9M/Rb/nUTc6UXc3VEo2bpQkDeiOh/G5t+RvStWrAT7Pd0FvaLU6SU+vpDwAoBZ2wuxinnwR3X1Soy6etsYC2Mv0Gtwe3PX+iPMTpHFT+twOl8HQP6WcMfsAMjd6+icFlEzDWQpQX0z0Xc+/R9t73bPdfpT0wzPAX6B0D3uE7fNaplLTQJ7kTWAEPBl6R0G0QWlnbkwsJc9ai6efFXqxRTRrDPniPRhRdUSWEGs4gNCoE5sM1gxaLxsTdVUzFdfV6pW8ZIYf6MeQGCGq107q/+Gfu2j0JnUlAgHoLhKxNV0E3MUaORJ4tiF1VG7WDXkjHZLMULV/QMog2aFQUKrBUUlMMl1PDlafLCC0mC3hRj15lQLkkHFB36Bu+UD5ws2if6nSheM0EnDPmY17FsZiKPFK48AK+nMjwvtGbXJjf0xTM27NL6A8tpa7zLsrdt9BIHCFdbGbDlRJcbVuGL7w6I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
